# Generated by Django 5.0.6 on 2024-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nilouser',
            },
        ),
    ]
