# Generated by Django 5.0.6 on 2024-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_song_alter_music_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='img/', verbose_name='Thumbnail'),
        ),
    ]
